### ISSUE TITLE
报错啊。。。

### ISSUE THREAD

**Issue by shizu2014** [wangtao2213405054/subscribe-subway#2]
2023-03-30 19:53:58,456 main.py[line:118] INFO 准备今天 20 抢明天的票!
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/huanglundun/Downloads/subscribe-subway-master/subway/main.py", line 180, in task
    _metro = metro.Metro(token)
NameError: name 'metro' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huanglundun/Downloads/subscribe-subway-master/subway/main.py", line 245, in <module>
    command()
  File "/usr/local/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click-8.1.3-py3.10.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/huanglundun/Downloads/subscribe-subway-master/subway/main.py", line 238, in command
    run(subscribeTime=subscribe, processes=processes, dingTalk=dingtalk, confPath=path)
  File "/Users/huanglundun/Downloads/subscribe-subway-master/subway/main.py", line 142, in run
    _result = list(map(lambda x: x.get(), task_result))
  File "/Users/huanglundun/Downloads/subscribe-subway-master/subway/main.py", line 142, in <lambda>
    _result = list(map(lambda x: x.get(), task_result))
  File "/usr/local/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'metro' is not defined

**Comment by wangtao2213405054** [comment]
看样子是运行时的问题，我需要确认一下是通过什么方式运行的，是否通过readme文档的方式运行的呢，可否提供一下详细的运行截图，最好可以看到项目路径

**Comment by wangtao2213405054** [comment]
看样子是运行时的问题，我需要确认一下是通过什么方式运行的，是否通过readme文档的方式运行的呢，可否提供一下详细的运行截图，最好可以看到项目路径

**Comment by shizu2014** [comment]
是的 完全按照readme运行的，中午的时候还报 logger.logger(logger.INFO)这个错误，然后我引入了import logger这个库。
晚上logger这个没报错误，但是又报了刚才那个错误
<img width="1089" alt="截屏2023-03-30 下午8 14 45" src="https://user-images.githubusercontent.com/10099006/228832750-73052ab4-7a9d-4f6e-a3f3-d759cedb81f5.png">

<img width="1089" alt="截屏2023-03-30 下午8 14 33" src="https://user-images.githubusercontent.com/10099006/228832738-f8042b61-179e-46ae-8325-c6572da44a07.png">

<img width="508" alt="截屏2023-03-30 下午8 14 02" src="https://user-images.githubusercontent.com/10099006/228832673-81007032-6442-47ac-99d9-1556c59b4993.png">

**Comment by wangtao2213405054** [comment]
稍等一会，一会我回去看一下

**Comment by wangtao2213405054** [comment]
问题已经修复，请重新 Clone 一下代码运行
问题原因：
Mac 系统适配问题
解决:
修改了导入模块的逻辑

**Comment by shizu2014** [comment]
好的
